'use client';

import { useState } from 'react';
import { Bot, Building2, BrainCircuit, ShieldCheck, Film, ArrowRight, ArrowUpRight, Check, Workflow, MousePointer2 } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';

const projects = [
  { id:'agents', label:'Agent workflows', icon:Bot, category:'01 / CONNECT THE WORK', title:'Less handoff. More progress.', summary:'I automate departmental workflows by connecting multiple agents, tools, and the people who make the final decisions.', contribution:'I translate the process into clear steps, orchestrate agents and tool connections, then use AI-assisted development to build, test, and deploy the workflow.', nodes:['Request','Agents + tools','Review','Action'], details:['Start with a real operational task and the context needed to complete it.','Coordinate focused agents, APIs, and MCP connections around the task.','Bring the right person into decisions that need judgment.','Deliver the result into the team’s working process.'], tags:['Multi-agent workflows','MCP & APIs','AI-assisted delivery'], outcome:'From disconnected tasks to a repeatable way of working.', status:'Internal workflow automation' },
  { id:'intranet', label:'Intranet', icon:Building2, category:'02 / GIVE TEAMS A HOME', title:'One place for everyday work.', summary:'I developed an in-house intranet for The Binary Holdings, bringing departmental work into a shared workspace.', contribution:'I connect the needs of different teams, shape the experience, and build the workflows with AI assistance—keeping the daily user journey at the center.', nodes:['Teams','Workspace','Workflow','Visibility'], details:['Understand how departments work and where handoffs get lost.','Give teams a shared home for their everyday work.','Connect steps into an organized process.','Make the progress of work easier to follow.'], tags:['Internal platform','Cross-functional workflows','Product thinking'], outcome:'A shared operating space for the people behind the products.', status:'In-house platform' },
  { id:'aria', label:'ARIA', icon:BrainCircuit, category:'03 / ADD INTELLIGENCE', title:'Context becomes a useful decision.', summary:'I contribute to the intelligence-layer work around ARIA at The Binary Labs, within The Binary Holdings.', contribution:'My focus is connecting business use cases to practical AI workflows, agent orchestration, and AI-assisted implementation alongside the team.', nodes:['Context','Reasoning','Decision','Feedback'], details:['Bring relevant context into a clearly defined business question.','Use the intelligence layer to reason over that context.','Connect the reasoning to a useful next step.','Feed what is learned back into the workflow.'], tags:['Intelligence layer','Agent orchestration','Collaborative delivery'], outcome:'Intelligence that fits into an existing workflow.', status:'Ongoing contribution', source:'https://www.thebinarylabs.ai/', sourceLabel:'Explore ARIA at The Binary Labs' },
  { id:'qa', label:'WaveGuard', icon:ShieldCheck, category:'04 / BUILD CONFIDENCE', title:'Many environments. One QA view.', summary:'I’m building an in-house QA platform around Appium and Playwright for mobile and web journeys across a distributed product ecosystem.', contribution:'I bring execution, evidence, monitoring, and AI-assisted analysis into one workflow, so teams can understand what was tested and what needs attention.', nodes:['Schedule','Execute','Evidence','Analyze'], details:['Define the journey, platform, and environment to check.','Run mobile and web checks with Appium and Playwright.','Collect screenshots, video, logs, and execution results.','Review failures with supporting evidence and AI-assisted analysis.'], tags:['Appium','Playwright','AI-assisted QA'], outcome:'A clearer path from a test run to an actionable finding.', status:'In-house QA platform' },
  { id:'content', label:'Content agents', icon:Film, category:'05 / MOVE CONTENT FORWARD', title:'Discovery to publishing, connected.', summary:'An AI agent workspace for Fando / ngage that connects content discovery, processing, approval, and CMS publishing.', contribution:'I bring the steps into a usable workflow, connecting AI-assisted content operations with the product and the people who manage it.', nodes:['Discover','Approve','Process','Publish'], details:['Bring relevant sports content into the discovery queue.','Review what should move forward.','Prepare clips and context-aware captions for the next step.','Connect approved content to the CMS publishing workflow.'], tags:['Fando / ngage','Content operations','CMS automation'], outcome:'One workflow from content discovery to the publishing queue.', status:'Internal agent workspace' },
];

function ProjectFlow({ project }: {project: typeof projects[number]}) {
  const [step, setStep] = useState(0);
  return <div className="story-project">
    <div className="story-project-copy"><span className="eyebrow">{project.category}</span><h3>{project.title}</h3><p>{project.summary}</p><div className="contribution"><span>MY CONTRIBUTION</span><p>{project.contribution}</p></div><div className="story-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>
    <div className="story-diagram"><div className="diagram-top"><span><project.icon size={17}/>{project.label}</span><span className="diagram-note">Workflow overview</span></div><div className="flow-track" aria-hidden="true"><span/><span/><span/></div><div className="flow-steps" aria-label={`${project.label} workflow steps`}>{project.nodes.map((node,index)=><button key={node} className={index===step?'selected':''} aria-pressed={index===step} onClick={()=>setStep(index)}><span className="flow-number">{String(index+1).padStart(2,'0')}</span><strong>{node}</strong><ArrowRight size={16}/></button>)}</div><div className="flow-explanation" aria-live="polite"><span className="flow-kicker">STEP {step+1} / {project.nodes.length}</span><h4>{project.nodes[step]}</h4><p>{project.details[step]}</p></div><p className="flow-hint"><MousePointer2 size={13}/>Select a step to explore</p></div>
    <div className="story-project-footer"><p><Check size={17}/>{project.outcome}</p><span>{project.status}</span></div>
    {project.source&&<a className="company-source" href={project.source} target="_blank" rel="noreferrer">{project.sourceLabel}<ArrowUpRight size={14}/></a>}
  </div>;
}

export function WorkStory() {
  return <><p className="section-intro">Different problems. The same approach: understand the work, connect the right tools, and make the result useful.</p><Tabs defaultValue="agents" className="work-explorer"><TabsList className="work-picker" aria-label="Explore my projects">{projects.map(project=><TabsTrigger key={project.id} value={project.id}><project.icon size={17}/>{project.label}</TabsTrigger>)}</TabsList>{projects.map(project=><TabsContent key={project.id} value={project.id}><ProjectFlow project={project}/></TabsContent>)}</Tabs><div className="ecosystem-note"><Workflow size={21}/><div><strong>Built in a connected ecosystem.</strong><p>The Binary Holdings spans operator apps and multiple markets. That context shapes my focus on reusable workflows, dependable testing, and tools that teams can actually use.</p><div><a href="https://www.thebinaryholdings.com/" target="_blank" rel="noreferrer">The Binary Holdings <ArrowUpRight size={13}/></a><a href="https://www.thebinarylabs.ai/" target="_blank" rel="noreferrer">The Binary Labs <ArrowUpRight size={13}/></a></div></div></div></>;
}

export function BuildMethod() {
  return <div className="build-method"><span className="eyebrow">HOW I TURN AN IDEA INTO A WORKFLOW</span><div>{[{n:'01',title:'Understand',text:'Start with the team, the friction, and the desired result.'},{n:'02',title:'Orchestrate',text:'Connect agents, prompts, tools, and APIs around the job.'},{n:'03',title:'Build with AI',text:'Use AI-assisted development to implement and iterate.'},{n:'04',title:'Validate & ship',text:'Check the journey, deploy, and refine with feedback.'}].map(item=><article key={item.n}><span>{item.n}</span><h4>{item.title}</h4><p>{item.text}</p></article>)}</div></div>;
}
